/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";
import Image from "next/image";
import nft from "../../public/nfts.png";

export const Container = styled.div`
  display: flex;
  flex-direction: column;
  margin-top: 10px;
  align-items: center;
  padding: 100px;
  font-size: 25px;

  small {
    display: flex;
  }
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Gustavo Fernandes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      &nbsp; I'm a self taught programmer, Currently focusing on the Crypto
      world. Throughout the years I created Android Apps with Java, models of
      Deep Learning with Python, AI with Javascript, but currently I'm focused
      on Crypto using technologies like Web3, Ethers, Hardhat, Solidity,
      Oracles, React, NextJS and so on. I'm now building DeFi and NFT DApps. I
      also build Backend servers with Node, made some bots with it.
      <br></br>
      <br></br>
      &nbsp; I speak English, French and Portuguese [currently learning Russian]
      . I like learning new things related to Science or new Technologies and on
      my free time I like to watch code magicians like Daniel Shiffman, CJ from
      The Coding Garden, George Hotz and off course, Patrick Collins.
      <br />
      &nbsp;
      {/* <div>I'm open for hiring or collaboration.</div> */}
      <div style={{ width: "70%", marginTop: "20px" }}>
        <Image src={nft} height={600}></Image>
      </div>
      <br></br>
      <br />
      <div>Discord: abhadira</div>
      <div>email: contato.gustavofernandes@hotmail.com</div>
      <br />
      <div style={{ marginBottom: "5px" }}>
        Linkedin:
        <Link href={"https://www.linkedin.com/in/gustavo-fernandes-48a49a130/"}>
          <a
            style={{
              color: "blue",
              textDecoration: "underline",
            }}
          >
            Gustavo Fernandes
          </a>
        </Link>
      </div>
      <div>
        Github:
        <Link href={"https://github.com/BronzeDisc"}>
          <a style={{ color: "blue", textDecoration: "underline" }}>
            My Projects
          </a>
        </Link>
      </div>
      <footer></footer>
    </Container>
  );
};

export default Home;
