/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import styled from 'styled-components'
import Image from 'next/image'
import nft from '../../public/nfts.png'

export const Container = styled.div`
  display: flex;
  flex-direction: column;
  margin-top: 10px;
  align-items: center;
  padding: 100px;
  font-size: 25px;

  small {
    display: flex;
  }
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Gustavo Fernandes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      &nbsp; I'm a self-taught programmer, currently focusing on the crypto
      world. Throughout the years, I have created Android apps with Java, models
      of deep learning with Python, and AI with JavaScript. Now, I'm solely
      focused on Ethereum, Solidity, and their intricacies. I have a lot of
      knowledge about the Ethereum blockchain and its deeper concepts. Another
      mission of mine is to become a specialist in Chainlink and its most
      important services.
      <br></br>
      <br></br>
      For the past year and a half, I've been working as a security auditor for
      smart contracts. I've contributed to protocols that manage hundreds of
      millions of dollars, some ensuring quality [e.g., Ondo Finance] and others
      identifying medium and high severity issues.
      <br></br>
      <br></br>
      &nbsp; I speak English, French, and Portuguese [currently learning
      Russian]. I enjoy learning new things related to science or new
      technologies. In my free time, I like to watch coding magicians like
      Daniel Shiffman, CJ from The Coding Garden, George Hotz, and of course,
      Patrick Collins.
      <br />
      &nbsp;
      {/* <div>I'm open for hiring or collaboration.</div> */}
      <div style={{ width: '70%', marginTop: '20px' }}>
        <Image src={nft} height={600}></Image>
      </div>
      <br></br>
      <br />
      {/* <div>Discord: bronzeDisc#9664</div> */}
      <div>email: contato.gustavofernandes@hotmail.com</div>
      <br />
      <div style={{ marginBottom: '5px' }}>
        Linkedin:
        <Link href={'https://www.linkedin.com/in/gustavo-fernandes-48a49a130/'}>
          <a
            style={{
              color: 'blue',
              textDecoration: 'underline',
            }}
          >
            Gustavo Fernandes
          </a>
        </Link>
      </div>
      <div>
        Github:
        <Link href={'https://github.com/0x-tsar'}>
          <a style={{ color: 'blue', textDecoration: 'underline' }}>
            My Projects
          </a>
        </Link>
      </div>
      <footer></footer>
    </Container>
  )
}

export default Home
